### ISSUE TITLE
Add Supprt for python3 and IDA pro 7.5

### ISSUE THREAD

**Issue by r0ny123** [hyuunnn/Hyara#12]
`Hyara` fails to work with `IDA pro 7.5` and `python3`. As `Python` 2 is no longer supported, it would be worth a update to `Hyara`.

**Comment by hyuunnn** [comment]
Some analysts do not use the latest version.
So I will develop code that supports both python 2 and 3.
This project was made a long time ago, so I will be refactoring it soon.

**Comment by hyuunnn** [comment]
@r0ny123 
Currently, support for IDA Pro, cutter, binaryninja has been completed.
I will release soon. :)

**Comment by hyuunnn** [comment]
@r0ny123 
Finished :)

**Comment by r0ny123** [comment]
Thnaks, man!
