### ISSUE TITLE
don't overwrite old releases please

### ISSUE THREAD

**Issue by psifertex** [hyuunnn/Hyara#20]
if you keep updating your old release but keeping the version number the same Binary Ninja users who use the plugin manager won't get any updates they need to update their plugin. You need to actually increment the plugin version number so that the plugin manager knows to update.

You might find this tool helpful for automating that:

https://github.com/vector35/release_helper

**Comment by hyuunnn** [comment]
sorry. I'll fix it

**Comment by psifertex** [comment]
Thanks! It's not a huge deal, just wanted to let you know so people will actually get the updates. Appreciate it.
