### ISSUE TITLE
Error in Yara Checker: 'yara.StringMatch' object is not subscriptable

### ISSUE THREAD

**Issue by ashley-920** [hyuunnn/Hyara#23]
Using yara-python-4.3.1 on IDA 8.3
Yara Checker raise `'yara.StringMatch' object is not subscriptable` error. 
This is probably because yara-python reports matches has changed between versions 4.2.3 and version 4.3.0. 
In version 4.2.3 matches the yara.Match object contained an attribute strings which was a list of Tuples. In version 4.3.0 (and presumably any future version) the match object contains an attribute strings which is a list of yara.StringMatchInstance values.

Similar issue: https://github.com/volatilityfoundation/volatility3/issues/932

**Comment by hyuunnn** [comment]
Thanks! I have midterms coming up next week.
I'll check it out after the exam.

**Comment by hyuunnn** [comment]
https://github.com/hyuunnn/Hyara/commit/292023d71f409fdce585f158c29f8e148b23d22e
@ashley-920 Fixed :)
