### ISSUE TITLE
Add support for radare2 and Cutter

### ISSUE THREAD

**Issue by XVilka** [hyuunnn/Hyara#8]
[Radare2](https://github.com/radareorg/radare2) is a highly-portable crossplatform reverse engineering framework and a toolkit without dependencies.  It has support for analyzing binaries, disassembling code, debugging programs, attaching to remote GDB/LLDB, WinDbg servers, rich plugin system (see `r2pm`), and integration with various decompilers. It is actively developed and can be easily integrated in various open source and commercial products. I believe, it will be highly beneficial to support these and provide a package for install from `r2pm`, see the package repository here: https://github.com/radareorg/radare2-pm

![image](https://user-images.githubusercontent.com/203261/68269641-7ae24e00-0095-11ea-95f2-cebbc7246954.png)

For documentation on writing plugins for radare2 see [Scripting](https://radare.gitbooks.io/radare2book/content/scripting/intro.html) and [Plugins](https://radare.gitbooks.io/radare2book/content/plugins/intro.html) Radare2 Book chapters. Radare2 already has a Yara plugins:
- `r2pm install r2yara` for installing Yara with [r2 plugin](https://r2yara.readthedocs.io/en/latest/) inside
- `r2pm install yara-r2` for installing [Yara plugin for radare2](https://github.com/radareorg/radare2-extras/tree/master/yara/yara) itself.
- `pcy` command of radare2 to print the data in the Yara format.

[Cutter](https://cutter.re/) is a crossplatform Qt/C++ GUI frontend to radare2:

![image](https://user-images.githubusercontent.com/203261/68269343-78332900-0094-11ea-8646-f6226cb6043f.png)

For documentation on writing plugins for Cutter see [the official tutorial](https://cutter.re/docs/plugins.html) and the [curated list](https://github.com/radareorg/cutter-plugins) of various popular plugins.

**Comment by hyuunnn** [comment]
I will develop after code refactoring.
Thank you for your suggestion.

**Comment by hyuunnn** [comment]
@XVilka
Currently, support for cutter, binaryninja has been completed.
I will release soon. :)
![image](https://user-images.githubusercontent.com/15611739/104203234-40312e00-546f-11eb-91f5-4026ff137daf.png)

**Comment by hyuunnn** [comment]
@XVilka Finished :)
![image](https://user-images.githubusercontent.com/15611739/104737779-0bcbb380-5788-11eb-8535-bf8d1e1bb9fc.png)
![image](https://user-images.githubusercontent.com/15611739/104737841-2140dd80-5788-11eb-91e2-a51d7bcf79db.png)
![image](https://user-images.githubusercontent.com/15611739/104737874-2a31af00-5788-11eb-8940-154426a5c204.png)
