### ISSUE TITLE
Update for Binary Ninja plugin manager

### ISSUE THREAD

**Issue by psifertex** [hyuunnn/Hyara#9]
Can you split out the Binary Ninja plugin as a sub module so that it can be directly added to the plugin manager? 

See: https://binary.ninja/2019/07/04/plugin-manager-2.0.html for more information.

**Comment by hyuunnn** [comment]
@psifertex 
Currently, support for cutter, binaryninja has been completed.
I will release soon. :)
I will add to plugin manager after released.

**Comment by psifertex** [comment]
Great, thanks for the update! Once you add the plugin.json and create the release you can always just update me here if that's easier instead of filing an issue on the community-plugin repo, but whatever is easiest for you works for me.

**Comment by psifertex** [comment]
Oh, one random thought -- you might be interested in this example if you wanted to, for example, save the resulting rule to the clipboard: https://gist.github.com/psifertex/6fbc7532f536775194edd26290892ef7#file-clipboard-py

**Comment by psifertex** [comment]
Just following up to see if it makes sense to be updated for the plugin manager to help users discover it more easily.

**Comment by psifertex** [comment]
*ping*

If it helps, I'm adding subfolder support to the BN plugin manager. If you're interested in a PR, it should be pretty straight forward. You can see the changes I made to the lighthouse plugin to support it (and that one was much more complicated because of some namespace issues): https://github.com/psifertex/lighthouse/

**Comment by hyuunnn** [comment]
@psifertex 
I am currently busy.
I'll try it when I have time.
Thanks for the suggestion !

**Comment by psifertex** [comment]
No worries. I'm happy to submit a PR if you're interested.

**Comment by XVilka** [comment]
@hyuunnn @psifertex would be nice to have it in 2022 😄

**Comment by psifertex** [comment]
@hyuunnn Are you interested will to do a PR? I'm willing to submit one if you don't mind, it would just require you to [create a release](https://binary.ninja/2019/07/04/plugin-manager-2.0.html#5-create-a-release)

**Comment by hyuunnn** [comment]
@psifertex Sure :)
I am currently serving in the military in South Korea, so I haven't been able to update.

**Comment by hyuunnn** [comment]
@psifertex thanks :)
I will edit the gif file later.

**Comment by psifertex** [comment]
Mind re-opening this? One last step would be to create the release for 2.2 as you did before for 2.1. Everything in the repo should be ready for the 2.2 release. Also, you might find: https://github.com/vector35/release_helper helpful for future releases.

Once that's done I'll add it to the plugin manager!

**Comment by psifertex** [comment]
Thanks! I've added the plugin to our release tracker so as soon as I see the release for 2.2 is done, I'll add it to the plugin manager. Let me know if you have any trouble with the release process.
